//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarOfTheMonth.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long ID { get; set; }
        public string NominationID { get; set; }
        public string EmployeeNumber { get; set; }
        public string DepartmentHeadID { get; set; }
        public string TQCHeadID { get; set; }
        public string EvaluatorID { get; set; }
        public Nullable<bool> IsNewAlert { get; set; }
        public Nullable<bool> IsNotification { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string AdminId { get; set; }
        public string Comments { get; set; }
    }
}
