//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarOfTheMonth.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpMaster
    {
        public int EmpID { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastLogedIn { get; set; }
        public string Position { get; set; }
        public string ImagePath { get; set; }
        public string CompanyName { get; set; }
        public string EmployeeEmail { get; set; }
        public string Contact { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> PositionsId { get; set; }
        public Nullable<int> ReportingPersonId { get; set; }
        public Nullable<System.DateTime> PasswordChangedOn { get; set; }
        public int UserRole { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Department { get; set; }
        public string UserName { get; set; }
        public string Grade { get; set; }
    }
}
