//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarOfTheMonth.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnumAbbreviation
    {
        public long ID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string ParentName { get; set; }
        public string ParentDescription { get; set; }
        public Nullable<long> ChildID { get; set; }
        public string ChildName { get; set; }
        public string ChildDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
