//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarOfTheMonth.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomination
    {
        public long ID { get; set; }
        public string EmployeeNumber { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string ProjectTitle { get; set; }
        public string Idea { get; set; }
        public string PrimaryObjective { get; set; }
        public string BriefDescription { get; set; }
        public string Benefits { get; set; }
        public Nullable<long> HorizontalDeploymentID { get; set; }
        public string Acknowledgement { get; set; }
        public string SubmittedMonth { get; set; }
        public string SubmittedYear { get; set; }
        public string NomSubmittedDate { get; set; }
        public string NomSignature { get; set; }
        public string DHComments { get; set; }
        public string DHSubmittedDate { get; set; }
        public string DHSignature { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string Savings { get; set; }
        public string Cost { get; set; }
        public string Time { get; set; }
        public string Paper { get; set; }
        public string UploadedFileNames { get; set; }
        public string NominationId { get; set; }
        public string SOMComments { get; set; }
        public string SOMSubmittedDate { get; set; }
        public string SOMSignature { get; set; }
    }
}
