//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarOfTheMonth.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long ID { get; set; }
        public string Category { get; set; }
        public string SourceUser { get; set; }
        public string DestinationUser { get; set; }
        public string Message { get; set; }
        public Nullable<bool> UserSeen { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
    }
}
